spring.application.name=demo

# MySQL
mysql.datasource.url=jdbc:mysql://localhost:3307/demo_mysql
mysql.datasource.username=root
mysql.datasource.password=password

# PostgreSQL DB
pgsql.datasource.url=jdbc:postgresql://localhost:5432/demo_postgresql
pgsql.datasource.username=postgres
pgsql.datasource.password=password

